version: '3.9'


# add audiobooksh
# https://github.com/advplyr/audiobookshelf
services:
  audiobookshelf:
    container_name: audiobooks
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    volumes:
      - /exposed/audiobooks:/audiobooks
      - /exposed/podcasts:/podcasts
      - /audiobookshelf/config:/config
      - /audiobookshelf/metadata:/metadata
