version: '3.9'


# add audiobooksh
# https://github.com/advplyr/audiobookshelf
services:
  audiobookshelf:
    container_name: audiobooks
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=997
      - AUDIOBOOKSHELF_GID=992
    volumes:
      - /data/audiobookshelf/audiobooks:/audiobooks
      - /data/audiobookshelf/podcasts:/podcasts
      - /data/audiobookshelf/config:/config
      - /data/audiobookshelf/metadata:/metadata
