version: '3.9'

services:
  # Add NFS
  # https://hub.docker.com/r/itsthenetwork/nfs-server-alpine
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest-arm
    container_name: nfs
    volumes:
      - /exposed:/exposed:z
    environment:
      - "SHARED_DIRECTORY=/exposed"
    privileged: true
    network_mode: host

  # Add Samba for Windows peeps
  # https://hub.docker.com/r/dperson/samba
  # config mostly lifted from: https://github.com/dperson/samba/blob/master/docker-compose.yml
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    command: " -u 'dataman;ilikemesomedata' -u 'public;4publicaccess' -s 'data;/exposed;yes;no;yes;all;none;dataman,public;' -n -r"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /exposed:/exposed:z
